name: Publish release

on:
  push:
    branches:
      - main
      - master
      - develop
  release:
    types:
      - published

jobs:
  publish:
    uses: Shane32/SharedWorkflows/.github/workflows/publish-nuget.yml@v1
    with:
      dotnet_folder: '.'
    secrets: inherit
