name: Run code tests

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build-check:
    uses: Shane32/SharedWorkflows/.github/workflows/build-check.yml@v1
    with:
      dotnet_folder: '.'
      coveralls: true
    secrets: inherit
